version: '3'

services:
  web:
    build: ./backend
    container_name: django-app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Keeps node_modules inside container
    command: sh -c "npm install && npm start"
