version: '3'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=test.admin@gmail.com
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3 
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Keeps node_modules inside container
    command: sh -c "npm install && npm start"
