# Generated by Django 5.1.6 on 2025-02-16 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('username_attempted', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_file', models.FileField(blank=True, null=True, upload_to='encrypted_uploads/')),
                ('encryption_key', models.BinaryField(blank=True, null=True)),
                ('iv', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('file_upload', 'File Upload'), ('file_download', 'File Download'), ('file_share', 'File Share'), ('access_revoke', 'Access Revoke'), ('user_login', 'User Login'), ('user_register', 'User Registration'), ('intrusion_alert', 'Intrusion Alert'), ('share_link_generated', 'Share Link Generated'), ('file_download_share_link', 'File Download via Share Link'), ('admin_file_list_viewed', 'Admin Viewed File List'), ('admin_file_deleted', 'Admin Deleted File')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_type', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('full', 'Full Access')], default='view', max_length=10)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='FileSharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('full', 'Full Access')], default='view', max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_permissions', to='files.file')),
                ('shared_with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'shared_with_user')},
            },
        ),
    ]
