# Generated by Django 5.1.6 on 2025-02-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='iv',
            new_name='iv_base64',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encryption_key',
        ),
        migrations.AddField(
            model_name='file',
            name='encryption_key_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='server_iv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
