# Generated by Django 5.1.6 on 2025-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_iv_file_iv_base64_remove_file_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablelink',
            name='encryption_key_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareablelink',
            name='iv_base64',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
