# Generated by Django 5.1.6 on 2025-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_shareablelink_encryption_key_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='server_encryption_key_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
